### ISSUE TITLE
Not working on minecraft 1.20.1

### ISSUE THREAD

**Issue by Stove-git** [hotsu0p/beyond-vanilla#7]
I've got Minecraft version 1.20.1 with Iris 1.7.2 latest version installed. Its refusing to load and i dont know why. 
deferred.fsh: deferred.fsh: ERROR: 0:58: " : syntax error, unexpected SAMPLE, expecting COMMA or SEMICOLONERROR: 1 compilation errors. No code generated.

**Comment by hotsu0p** [comment]
You using any more mods?

**Comment by Stove-git** [comment]
yeah, but its not coz of them
also im using sodium and iris if thats the problem

**Comment by hotsu0p** [comment]
Can you show me your mod list and the crash log?
